### ISSUE TITLE
- [ ] Realizar Prototipo baja o mediana fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#10]

**Comment by JohnFlorez25** [comment]
Mariana recuerda no cerrarme las actividades , yo las cierro una vez que las apruebe.
Gracias 

By John Flórez

**Comment by JohnFlorez25** [comment]
@Mariana1013 @WilfranMarin el prototipo debe mostrar todos los aspectos relacionados y aprobados en el primer cuadrante, hay que tener presente una zona de informes y reportes donde se muestren el estado actual de acuerdo a los usuarios que han suministrado información en la aplicación, y que además pueda seguir brindando una información de seguimiento.

**Comment by WilfranMarin** [comment]
https://drive.google.com/drive/u/0/folders/1YZd-XBKAHTbUXCEaNmc8RsOItKb0U9PW
