### ISSUE TITLE
- [ ] Realizar validaciones con 5 usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#11]

**Comment by WilfranMarin** [comment]
https://github.com/JohnFlorez25/equipo5_sa_ppi2020/projects/1#card-42764228

**Comment by WilfranMarin** [comment]
https://drive.google.com/file/d/1B6zcC79w9VHwAH51TZdQupcwZNnV6AIZ/view?usp=sharing

**Comment by WilfranMarin** [comment]
https://drive.google.com/file/d/12Z3gVStKgSgAmHBkPScd-6-4tbWhthH-/view?usp=sharing
