### ISSUE TITLE
- [ ] Realizar cuadro de objetos aplicando metodología OOUX

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#12]

**Comment by JohnFlorez25** [comment]
@WilfranMarin @Mariana1013 @jennymontoya1001 Revisar el cuadro de OOUX que sea coherente los objetos con sus acciones, de acuerdo a lo que hablamos podemos identificar tres objetos principales:
- USUARIO CON PROBLEMA DE AGUA POTABLE
- AUXILIAR QUE VA A REALIZAR CARACTERIZACIÓN DEL USUARIO QCON PROBLEMA DE AGUA POTABLE SIN ACCESO A INTERNET Y/O DISPOSITIVO WEB / MOBILE
- REPORTES

**Comment by Mariana1013** [comment]
@JohnFlorez25 acabo de subir el cuadro de OOUX
