### ISSUE TITLE
- [ ] Hacer flujo de tareas por funcionalidades

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#13]

**Comment by JohnFlorez25** [comment]
@WilfranMarin @Mariana1013 @jennymontoya1001 no esta la evidencia del flujo de actividades del segundo cuadrante

**Comment by Mariana1013** [comment]
@JohnFlorez25 @jennymontoya1001 esta tarea ya se encuentra realizada
