### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@WilfranMarin @Mariana1013 para dentro de 8 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con la profesora @jennymontoya1001  y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo
![modelo-e-r](https://user-images.githubusercontent.com/22262727/94061535-24642800-fdab-11ea-8b40-3c164c643040.png)

**Comment by JohnFlorez25** [comment]
@Mariana1013 @jennymontoya1001 @WilfranMarin no se ha subido el modelo entidad - relación a la wiki como evidencia de la implementación de este

**Comment by Mariana1013** [comment]
@JohnFlorez25 @jennymontoya1001 ya quedo lista esta actividad.
