### ISSUE TITLE
- [ ] Definir los servicios del Backend que se deben implementar de acuerdo con las reglas de negocio. (Objeto JSON)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#17]

**Comment by JohnFlorez25** [comment]
@WilfranMarin @Mariana1013 El siguiente formato se especifica la estructura de como deben evidenciar cada uno de los servicios backend que van a ser consumidos desde el frontend (validar con la profe jenny @jennymontoya1001 )
[Uploading Formato Definición de los servicios backend.docx…]()

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @WilfranMarin @Mariana1013 no esta la evidencia con el documento de la definición de los servicios backend

**Comment by Mariana1013** [comment]
@JohnFlorez25  @jennymontoya1001 esta tarea esta realizada.
