### ISSUE TITLE
- [ ] Construcción de la BD haciendo uso de MySQL

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#19]

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @WilfranMarin @Mariana1013 deben crear una carpeta llamada **bd** donde esten alojados los scripts para la creación de la base de datos

**Comment by Mariana1013** [comment]
@JohnFlorez25 @jennymontoya1001 ya esta actividad se encuentra en la wiki para ser revisada.

**Comment by JohnFlorez25** [comment]
@Mariana1013 @jennymontoya1001 @WilfranMarin deben garantizar que exista una carpeta llamada **bd** en el repositorio con los scripts de creación de la base de datos, por otro lado dejar una evidencia del diagrama que se genera en phpmyadmin de la base de datos garantizando la creación de esta y que tengan la base de datos en **clever cloud** esto es importante ya que el producto realizado debe quedar disponible para cualquier persona que desee ir a ver la aplicación.
