### ISSUE TITLE
Realizar Historias de Usuario y criterios de aceptación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#8]

**Comment by JohnFlorez25** [comment]
@WilfranMarin @Mariana1013 las historias de usuario deben ser mínimo 10, estás deben evidenciar las funcionalidades claves de su aplicación, es muy importante que tengan en cuenta que la aplicación no solo debe permitir realizar un registro sino que el usuario que la utilice nos brinde información constante y de monitoreo, de esta forma también poder ver detalles de los datos que ha recopilado la aplicación gracias a las demás personas que hacen uso de ella y mostrar esta información en tiempo real, esto bajo el  principio de que funcione de acuerdo a como funciona la aplicación de referencia CoronaAPP

**Comment by WilfranMarin** [comment]
https://drive.google.com/file/d/1Ay4pfDurnAASEqbugrjmaLXfnR03f3Ep/view?usp=sharing
