### ISSUE TITLE
- [ ] Hacer mapa de Historia de Usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sa_ppi2020#9]
https://drive.google.com/drive/u/0/folders/1YZd-XBKAHTbUXCEaNmc8RsOItKb0U9PW

**Comment by JohnFlorez25** [comment]
@WilfranMarin @Mariana1013 @jennymontoya1001 no han realizado el mapa de historias de usuarios del segundo cuadrante

**Comment by Mariana1013** [comment]
@JohnFlorez25 @jennymontoya1001 esta actividad ya se encuentra realizada
